import Head from "next/head";
import {
  Container,
  Main,
  Title,
  Description,
  Summary,
  UserList,
  StyledTable,
} from "../components/sharedstyles";
import Link from "next/link";
import Cards from "../components/cards";

export async function getServerSideProps() {
  const signupsRes = await fetch("http://localhost:3000/api/signups");
  const signups = await signupsRes.json();

  signups.sort((a, b) => b.signupDate.localeCompare(a.signupDate));

  const loginsRes = await fetch("http://localhost:3000/api/logins");
  const logins = await loginsRes.json();

  const upgradesRes = await fetch("http://localhost:3000/api/upgrades");
  const upgrades = await upgradesRes.json();

  return { props: { signups, logins, upgrades } };
}

export default function Home({ signups, logins, upgrades }) {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <Title>
          Welcome to the{" "}
          <a href="https://github.com/samwellai/nextjs-test#nextjs-test">
            Samwell AI Test!
          </a>
        </Title>

        <Summary>
          <p>New Signups: {signups.length}</p>
          <p>Logins: {logins.length}</p>
          <p>Upgrades: {upgrades.length}</p>
        </Summary>
        <StyledTable>
          <thead>
            <tr>
              <th>Name</th>
              <th>Signup Date</th>
            </tr>
          </thead>
          <tbody>
            {signups.map((user) => (
              <tr key={user.id}>
                <td>
                  <Link href={`/users/${user.id}`}>{user.name}</Link>
                </td>
                <td>{user.signupDate}</td>
              </tr>
            ))}
          </tbody>
        </StyledTable>

        <Cards />
      </Main>
    </Container>
  );
}
