import Head from "next/head";
import {
  Container,
  Main,
  Title,
  Summary,
  StyledTable,
} from "../components/sharedstyles";
import Link from "next/link";
import Cards from "../components/cards";
import { Signup, Login, Upgrade } from "../types/api";

interface HomeProps {
  signups: Signup[];
  logins: Login[];
  upgrades: Upgrade[];
}

export async function getServerSideProps() {
  const fetchAndHandleError = async (url: string) => {
    const response = await fetch(url);
    if (!response.ok) {
      throw new Error(`Failed to fetch data from ${url}`);
    }
    return response.json();
  };

  let signups: Signup[] = [];
  let logins: Login[] = [];
  let upgrades: Upgrade[] = [];

  try {
    signups = await fetchAndHandleError("http://localhost:3000/api/signups");
    logins = await fetchAndHandleError("http://localhost:3000/api/logins");
    upgrades = await fetchAndHandleError("http://localhost:3000/api/upgrades");

    signups.sort((a, b) => b.signupDate.localeCompare(a.signupDate));
  } catch (error) {
    console.error("Error fetching data:", error);
    return {
      notFound: true,
    };
  }

  return { props: { signups, logins, upgrades } };
}

export default function Home({ signups, logins, upgrades }: HomeProps) {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <Title>
          Welcome to the{" "}
          <a href="https://github.com/samwellai/nextjs-test#nextjs-test">
            Samwell AI Test!
          </a>
        </Title>

        <Summary>
          <p>New Signups: {signups.length}</p>
          <p>Logins: {logins.length}</p>
          <p>Upgrades: {upgrades.length}</p>
        </Summary>
        <StyledTable>
          <thead>
            <tr>
              <th>Name</th>
              <th>Signup Date</th>
            </tr>
          </thead>
          <tbody>
            {signups.map((user) => (
              <tr key={user.id}>
                <td>
                  <Link href={`/users/${user.id}`}>{user.name}</Link>
                </td>
                <td>{user.signupDate}</td>
              </tr>
            ))}
          </tbody>
        </StyledTable>

        <Cards />
      </Main>
    </Container>
  );
}
